"""
Utility modules for SecuriScan.

This package provides utility modules for the SecuriScan framework.
"""

from securiscan.utils.http import (
    create_user_agent,
    detect_waf,
    extract_form_data,
    extract_urls_from_html,
    extract_urls_from_js,
    get_base_url,
    get_domain,
    get_ssl_info,
    is_rate_limited,
    is_same_domain,
    is_subdomain,
    normalize_url,
    parse_cookies,
    parse_query_string,
)
from securiscan.utils.validation import (
    is_valid_base64,
    is_valid_cidr,
    is_valid_credit_card,
    is_valid_date,
    is_valid_datetime,
    is_valid_directory_path,
    is_valid_domain,
    is_valid_email,
    is_valid_file_path,
    is_valid_hex_string,
    is_valid_hostname,
    is_valid_http_header_name,
    is_valid_http_method,
    is_valid_http_status_code,
    is_valid_ip,
    is_valid_ip_range,
    is_valid_iso8601,
    is_valid_json_string,
    is_valid_mac_address,
    is_valid_md5,
    is_valid_phone_number,
    is_valid_port,
    is_valid_sha1,
    is_valid_sha256,
    is_valid_ssn,
    is_valid_time,
    is_valid_url,
    is_valid_uuid,
    is_valid_xml_string,
)

__all__ = [
    # HTTP utilities
    "normalize_url",
    "get_base_url",
    "get_domain",
    "is_same_domain",
    "is_subdomain",
    "extract_urls_from_html",
    "extract_urls_from_js",
    "extract_form_data",
    "get_ssl_info",
    "parse_cookies",
    "parse_query_string",
    "create_user_agent",
    "detect_waf",
    "is_rate_limited",
    
    # Validation utilities
    "is_valid_url",
    "is_valid_ip",
    "is_valid_domain",
    "is_valid_email",
    "is_valid_port",
    "is_valid_ip_range",
    "is_valid_mac_address",
    "is_valid_hostname",
    "is_valid_uuid",
    "is_valid_cidr",
    "is_valid_http_method",
    "is_valid_http_header_name",
    "is_valid_http_status_code",
    "is_valid_file_path",
    "is_valid_directory_path",
    "is_valid_json_string",
    "is_valid_xml_string",
    "is_valid_base64",
    "is_valid_hex_string",
    "is_valid_md5",
    "is_valid_sha1",
    "is_valid_sha256",
    "is_valid_credit_card",
    "is_valid_ssn",
    "is_valid_phone_number",
    "is_valid_date",
    "is_valid_time",
    "is_valid_datetime",
    "is_valid_iso8601",
]
